export type { Result, Success, Failure, FailureKind, FailureOptions } from './result'
export { ok, fail } from './result'
export { ScraperError, HttpError } from './errors'
export type { FailureClassification } from './failure'
export { classifyError, failFrom, describeFailure } from './failure'
export type { Logger } from './logger'
export { silentLogger, consoleLogger } from './logger'
export type { FetchLike, HttpClientOptions } from './http'
export { HttpClient, DEFAULT_USER_AGENTS } from './http'
export type { ScraperOptions } from './options'
export { BaseScraperService, clampSimilarity } from './options'
export { getSimilarity, getMatchScore, normalize } from './similarity'
